try to make the tools more reobust

diff --git a/LCA2019/scripts/genslides b/LCA2019/scripts/genslides
--- a/LCA2019/scripts/genslides
+++ b/LCA2019/scripts/genslides
@@ -1,18 +1,34 @@
 #!/bin/sh
 
-SLIDEDIR=slides
-
-if [ $1 = "-f" ]; then
+if [ "$1" = "-f" ]; then
   shift
   files=`cat $1`
 else
   files=$*
 fi
-if [ -d $SLIDEDIR ]; then
-	cd $SLIDEDIR || exit 2
+
+# use the location of this script to setup paths if needed
+if [ "$SLIDEDIR" = "" ]; then
+	[ "$PROJDIR" = "" ] && PROJDIR="`dirname $0`/../.."
+	SLIDEDIR="$PROJDIR/LCA2019/slides"
 fi
+
+#if [ -d $SLIDEDIR ]; then
+#	cd $SLIDEDIR || exit 2
+#fi
 #      {printf "incode: %d, inaside: %d inslide: %d\n", incode, inaside, inslide}
-cat $files \
+slidefiles=""
+for i in $files; do
+	f="$i"
+	[ ! -f "$i" ] && f="$SLIDEDIR/`basename $i`"
+	if [ ! -f "$f" ]; then 
+		echo "cannot find '$i' or '$f'"
+		exit 1;
+	fi
+	slidefiles="$slidefiles $f"
+done
+
+cat $slidefiles \
 	| tr '\t' '`' \
 	| awk -F\` '
       BEGIN { printf "<div class=\"slides\">\n"; inslide = 0; incode = 0; inaside = 0; slideNum = 0;}
diff --git a/LCA2019/scripts/insert b/LCA2019/scripts/insert
--- a/LCA2019/scripts/insert
+++ b/LCA2019/scripts/insert
@@ -5,7 +5,6 @@
 START_MARK=' include user data between here... '
 END_MARK=' ... and here '
 
-
 if [ ! -r "$1" ]; then
   echo usage: `basename $0` master-file [ snippet-file ]
   exit 2
@@ -14,14 +13,23 @@ fi
 master="$1"
 snippet=$2
 
-cp "$master" "$master".bak
+if [ ! -f "$master" ]; then
+	echo "can't file master file $master"
+	exit 1
+fi
+if [ ! -f "$snippet" ]; then
+	echo "can't file snippet file $snippet"
+	exit 1
+fi
+
+cp "$master" "$master".bak || exit 3
 
 cat "$master" | awk -v marker="$START_MARK" '
 	seen != 1 {print}
   $0 ~ marker {seen = 1}
-' > "$master".new
+' > "$master".new || exit 4
 
-cat $snippet >> "$master".new
+cat $snippet >> "$master".new || exit 5
 
 cat "$master" | awk -v marker="$END_MARK" '
   $0 ~ marker {seen = 1}
diff --git a/LCA2019/scripts/render b/LCA2019/scripts/render
--- a/LCA2019/scripts/render
+++ b/LCA2019/scripts/render
@@ -1,24 +1,65 @@
 #!/bin/bash
 #
-# render some slides to create a presentation
+if [ "$1" = "--wiz" ]; then
+ cat <<EOW
+-f listfile  name of a file containing the slides to be presented
+-o output  name of the output html file
+EOW
+ exit
+ fi
 
+listfile=
+output=
+[ -r defaults.sh ] && . defaults.sh
+args=`getopt f:o: -- "$@"`
+if [ $? != 0 ]; then 
+ echo "Valid options: "
+  $0 --wiz 
+ exit 2 
+ fi
+
+#set -- $args
+ for i
+ do
+  case "$i"
+   in
+-f) #  name of a file containing the slides to be presented
+     listfile="$2"; shift;  shift;
+   ;;
+-o) #  name of the output html file
+     output="$2"; shift;  shift;
+   ;;
+  --)
+    shift; break
+   esac
+done
+#
+#
+# insert your code here
+#echo listfile=$listfile
+#echo output=$output
+
+#trap 'mv /tmp/genslides.$$ /tmp/a' 0 1 2 15
 trap 'rm -f /tmp/genslides.$$' 0 1 2 15
 
+# render some slides to create a presentation
+
 function usage() {
-	echo "usage: $0 target-html [-f presentation-file] [ slide-file ...]"
+	echo "usage: $0 [-f presentation-file] [ -o output-file ] [ slide-file ...]"
 }
 
-if [ "$2" = "" ]; then
-	usage
-  exit 1;
-fi
+[ "$output" = "" ] && output=index.html
 
-targetfile="$1"
-CMDDIR="`dirname $0`"
-SERVERDIR="$CMDDIR/../../server"
-PRESENTATIONDIR="$CMDDIR/../presentations"
+# use the location of this script to setup paths if needed
+[ "$PROJDIR" = "" ] && PROJDIR="`dirname $0`/../.."
+
+targetfile="$output"
+CMDDIR="$PROJDIR/LCA2019/scripts"
+SERVERDIR="$PROJDIR/server"
+PRESENTATIONDIR="$PROJDIR/LCA2019/presentations"
 HOME="`pwd`"
 CONFDIR="`basename $HOME`"
+SLIDEDIR=$PROJDIR/LCA2019/slides
 
 if [ ! -d "$SERVERDIR" ]; then
 	echo "can't find the server directory, expect it to be at $SERVERDIR"
@@ -30,16 +71,37 @@ if [ ! -d "$PRESENTATIONDIR" ]; then
 	exit 2
 fi
 
-shift
+slidelist=""
+[ ! "$listfile" = "" ] && slidelist="`cat $listfile`"
+
+#[ ! "$listfile" = "" ] && listfile="-f $HOME/$listfile"
+#if [ ! -f $listfile ] ; then
+#  echo "cannot file slide list file $listfile"
+#  exit 2
+#fi
+
+for i in $slidelist $*; do
+	f="$i"
+	[ ! -f "$i" ] && f="$SLIDEDIR/$i"
+	if [ ! -f "$f" ]; then 
+		echo "cannot find '$i' or '$f'"
+		exit 1;
+	fi
+	slidefiles="$slidefiles $f"
+done
 
 cp $SERVERDIR/master.html "$PRESENTATIONDIR/$targetfile" || exit 3
-"$CMDDIR"/genslides $* >/tmp/genslides.$$ || exit 4
+"$CMDDIR"/genslides $slidefiles  >/tmp/genslides.$$ || exit 4
+
 "$CMDDIR"/insert "$PRESENTATIONDIR/$targetfile" /tmp/genslides.$$
+[ $? -eq 0 ] || exit $?
 
 cd $SERVERDIR
 
 # create symbolic link to the presentation in the server dir
+ln -sf ../LCA2019/presentations/"$targetfile" index.html
+echo "presentation can be accessed from: http://localhost:8000/"
 if [ ! -L "$targetfile" ]; then
-	ln -s ../$CONFDIR/presentations/"$targetfile" "$targetfile"
-	echo "created symbolic link. presentation can be accessed from: http://localhost:8000/$targetfile"
+	ln -s ../LCA2019/presentations/"$targetfile" "$targetfile"
+	echo "created symbolic link. presentation can also be accessed from: http://localhost:8000/$targetfile"
 fi
